const properties = [
  //we are adding a constant for the properties, each is unique and has different values
  {
    image: "images/img-1.jpg",
    type: "Studio",
    title: "Kapelstraat 68 C",
    rent: 420,
    subTitle: "5591 HG, Heeze",
    id: 0,
    allImages: ["images/img-1.jpg", "images/img-1.jpg", "images/img-1.jpg"],
  },
  {
    image: "images/img-2.jpg",
    type: "House",
    title: "Wattstraat 23 kamer 7",
    rent: 650,
    subTitle: "5621 AH, Eindhoven",
    id: 1,
    allImages: ["images/img-2.jpg", "images/img-2.jpg", "images/img-2.jpg"],
  },
  {
    image: "images/img-3.jpg",
    type: "Apartment",
    title: "Dasstraat 26 Kamer 4",
    rent: 830,
    subTitle: "5622 AS, Eindhoven",
    id: 2,
    allImages: ["images/img-3.jpg", "images/img-3.jpg", "images/img-3.jpg"],
  },
  {
    image: "images/room1.png",
    type: "Room",
    title: "Daumierstraat 151",
    rent: 520,
    subTitle: "5623 EV, Eindhoven",
    id: 3,
    allImages: ["images/room1.png", "images/room1.png", "images/room1.png"],
  },
  {
    image: "images/studio1.jpg",
    type: "Studio",
    title: "Hebronstraat 43",
    rent: 580,
    subTitle: "5625 PL, Eindhoven",
    id: 4,
    allImages: [
      "images/studio1.jpg",
      "images/studio1.jpg",
      "images/studio1.jpg",
    ],
  },
  {
    image: "images/house1.jpg",
    type: "House",
    title: "Breitnerstraat 20",
    rent: 920,
    subTitle: "5613 LA, Eindhoven",
    id: 5,
    allImages: ["images/house1.jpg", "images/house1.jpg", "images/house1.jpg"],
  },
  {
    image: "images/apartment1.jpeg",
    type: "Apartment",
    title: "Burghstraat 75",
    rent: 1000,
    subTitle: "5614 BB, Eindhoven",
    id: 6,
    allImages: [
      "images/apartment1.jpeg",
      "images/apartment1.jpeg",
      "images/apartment1.jpeg",
    ],
  },
  {
    image: "images/room2.jpg",
    type: "Room",
    title: "Rodenburgweg 120",
    rent: 380,
    subTitle: "5652 XB, Eindhoven",
    id: 7,
    allImages: ["images/room2.jpg", "images/room2.jpg", "images/room2.jpg"],
  },
  {
    image: "images/studio2.jpg",
    type: "Studio",
    title: "Limousinlaan 51",
    rent: 610,
    subTitle: "5627 KH, Eindhoven",
    id: 8,
    allImages: [
      "images/studio2.jpg",
      "images/studio2.jpg",
      "images/studio2.jpg",
    ],
  },
  {
    image: "images/apartament2.jpg",
    type: "House",
    title: "Kuiperbergstraat 195",
    rent: 1000,
    subTitle: "5628 DK, Eindhoven",
    id: 9,
    allImages: [
      "images/apartament2.jpg",
      "images/apartament2.jpg",
      "images/apartament2.jpg",
    ],
  },
  {
    image: "images/house2.jpg",
    type: "Apartment",
    title: "Vluttersven 41",
    rent: 1000,
    subTitle: "5646 HX, Eindhoven",
    id: 10,
    allImages: ["images/house2.jpg", "images/house2.jpg", "images/house2.jpg"],
  },
  {
    image: "images/room3.jpeg",
    type: "Room",
    title: "Girondelaan 2",
    rent: 430,
    subTitle: "5627 NG, Eindhoven",
    id: 11,
    allImages: ["images/room3.jpeg", "images/room3.jpeg", "images/room3.jpeg"],
  },
  {
    image: "images/studio3.jpg",
    type: "Studio",
    title: "Boschdijk 13",
    rent: 380,
    subTitle: "5621 JB, Eindhoven",
    id: 12,
    allImages: [
      "images/studio3.jpg",
      "images/studio3.jpg",
      "images/studio3.jpg",
    ],
  },
  {
    image: "images/house3.jpg",
    type: "House",
    title: "Huiskesweg 16",
    rent: 1000,
    subTitle: "5652 BC, Eindhoven",
    id: 13,
    allImages: ["images/house3.jpg", "images/house3.jpg", "images/house3.jpg"],
  },
  {
    image: "images/apartment3.jpg",
    type: "Apartment",
    title: "Insulindelaan 7",
    rent: 950,
    subTitle: "5631 AB, Eindhoven",
    id: 14,
    allImages: [
      "images/apartment3.jpg",
      "images/apartment3.jpg",
      "images/apartment3.jpg",
    ],
  },
  {
    image: "images/room4.jpg",
    type: "Room",
    title: "Minckelersplein 34",
    rent: 380,
    subTitle: "5621 EE, Eindhoven",
    id: 15,
    allImages: ["images/room4.jpg", "images/room4.jpg", "images/room4.jpg"],
  },
  {
    image: "images/studio4.jpg",
    type: "Studio",
    title: "Ruwenberg 111",
    rent: 430,
    subTitle: "5653 PT, Eindhoven",
    id: 16,
    allImages: [
      "images/studio4.jpg",
      "images/studio4.jpg",
      "images/studio4.jpg",
    ],
  },
  {
    image: "images/house4.jpg",
    type: "House",
    title: "Sterkenburg 112",
    rent: 980,
    subTitle: "5653 ND, Eindhoven",
    id: 17,
    allImages: ["images/house4.jpg", "images/house4.jpg", "images/house4.jpg"],
  },
  {
    image: "images/apartment4.jpg",
    type: "Apartment",
    title: "Dordognelaan 44",
    rent: 830,
    subTitle: "5627 HJ, Eindhoven",
    id: 18,
    allImages: [
      "images/apartment4.jpg",
      "images/apartment4.jpg",
      "images/apartment4.jpg",
    ],
  },
  {
    image: "images/room5.jpg",
    type: "Room",
    title: "Compiegnehof 196",
    rent: 420,
    subTitle: "5627 NN, Eindhoven",
    id: 19,
    allImages: ["images/room5.jpg", "images/room5.jpg", "images/room5.jpg"],
  },
  {
    image: "images/studio5.jpg",
    type: "Studio",
    title: "Keizersmantelstraat",
    rent: 660,
    subTitle: "5641 BM, Eindhoven",
    id: 20,
    allImages: [
      "images/studio5.jpg",
      "images/studio5.jpg",
      "images/studio5.jpg",
    ],
  },
  {
    image: "images/apartment5.jpg",
    type: "House",
    title: "Vestdijk 118",
    rent: 900,
    subTitle: "5611 CE, Eindhoven",
    id: 21,
    allImages: [
      "images/apartment5.jpg",
      "images/apartment5.jpg",
      "images/apartment5.jpg",
    ],
  },
  {
    image: "images/house5.jpg",
    type: "Apartment",
    title: "Neumannlaan 99",
    rent: 650,
    subTitle: "5624 KL, Eindhoven",
    id: 22,
    allImages: ["images/house5.jpg", "images/house5.jpg", "images/house5.jpg"],
  },
  {
    image: "images/room6.jpg",
    type: "Room",
    title: "Hobokenlaan 81",
    rent: 500,
    subTitle: "5628 VA, Eindhoven",
    id: 23,
    allImages: ["images/room6.jpg", "images/room6.jpg", "images/room6.jpg"],
  },
];
